services:
  postgres:
    image: postgres:15
    container_name: postgres-express-it
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: express-it
    ports:
      - "5433:5432"
    volumes:
      - express-it_postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-express-it
    ports:
      - "6380:6379"
    volumes:
      - express-it_redis:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-express-it
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  express-it_postgres:
  express-it_redis:
